name: Java CI with Maven

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8.0.332+9
      - name: "compile"
        run: mvn compile
      - name: "test"
        run: mvn test
      - name: Test with JaCoCo
        run: mvn test jacoco:report
      - name: Report to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
        run: mvn coveralls:report
